export const A = {
  DADO: {
    PODER_DADO: "poder-dado",
    NUM_DADO: "num-dado",
    HANDLE_NUMERO_DADOS: "handle-numero-dados",
    DADOS_FUTUROS: "dados-futuros",
    PODER_DADO_CASILLERO: "poder-dado-casillero",
    ROLL_ALL: " roll-all",
    ESPECIAL: "especial",
    LOCK: "lock",
    ACTIVACION_DADO: "activacion-dado",
    MODO_DADO: "modo-dado",
    NEGATIVO: "negativo",
  },
  STATS: {
    MOD_VIDA: "mod-vida",
    EXCESO_ENERGIA: "exceso-energia",
    BONUS_VIDA: "bonus-vida",
    PORCENTAJE_VIDA: "porcentaje-vida",
    HANDLE_IRA: "handle-ira",
    IRA_DADOS: "ira-dados",
    CALCULAR_STATS: "calcular-stats",
    MODIFICAR_EQUIPO: "modificar-equipo",
    ACTIVAR_SKILL: "activar-skill",
    MUERTE: "muerte",
  },
  BUFF: {
    EFECTOS_PS: "efectos-ps",
    PSICOSIS: "psicosis",
    CONTAGIO_PESTE: "peste",
    CORRUPCION: "corrupcion",
    CONFUSION: "confusion",
  },
  GRAL: {
    SELECCION_PERSONAJE: "seleccion-personaje",
    MOD_CASILLERO: "mod-casillero",
    TOGGLE_TURNO: "toggle-turno",
    AUTOMATICO: "automatico",
    DESPLEGABLE: "desplegable",
    MOD_DESPLEGABLE: "mod-desplegable",
  },
};

export const ACCIONES = {
  SELECCION_PERSONAJE: "seleccion-personaje",
  PODER_DADO: "poder-dado",
  NUM_DADO: "num-dado",
  HANDLE_NUMERO_DADOS: "handle-numero-dados",
  PODER_DADO_CASILLERO: "poder-dado-casillero",
  ROLL_ALL: " roll-all",
  ESPECIAL: "especial",
  LOCK: "lock",
  STATS: {
    MOD_VIDA: "mod-vida",
    EXCESO_ENERGIA: "exceso-energia",
    BONUS_VIDA: "bonus-vida",
  },
  PORCENTAJE_VIDA: "porcentaje-vida",
  HANDLE_IRA: "handle-ira",
  MOD_CASILLERO: "mod-casillero",
  MODO_DADO: "modo-dado",
  ACTIVACION_DADO: "activacion-dado",
  TOGGLE_TURNO: "toggle-turno",
  IRA_DADOS: "ira-dados",
  AUTOMATICO: "automatico",
  DESPLEGABLE: "desplegable",
  MOD_DESPLEGABLE: "mod-desplegable",
  PSICOSIS: "psicosis",
  CALCULAR_STATS: "calcular-stats",
  MODIFICAR_EQUIPO: "modificar-equipo",
  ACTIVAR_SKILL: "activar-skill",
  EFECTOS_PS: "efectos-ps",
  NEGATIVO: "negativo",
  CONTAGIO_PESTE: "peste",
  CORRUPCION: "corrupcion",
};
