const MODELO_EQUIPO = {
  ARMA: {
    nombre: "",
    ataque: 0,
    defensa: 0,
    critico: 0,
    maleficio: 0,
    curacion: 0,
    vampirismo: 0,
  },
  ARMADURA: {
    nombre: "",
    defensa: 0,
    esquivar: 0,
    maleficio: 0,
    curacion: 0,
    regeneracion: 0,
  },
  JOYA: {
    nombre: "",
    ataque: 0,
    defensa: 0,
    esquivar: 0,
    critico: 0,
    maleficio: 0,
    curacion: 0,
    regeneracion: 0,
  },
};

export const EFECTOS_EQUIPO = {
  VIDA_ATAQUE: "+5 de ataque cada 20 puntos de vida perdidos",
  VIDA_REGEN: "+1 regeneracion cada 20 puntos de vida perdidos",
  VIDA_RESURRECCION:
    "Por solo 1 vez, al quedar por debajo de 1HP te curas el 100% de la vida",
  REGEN_STATS: "+2 Ataque y Maleficio x cada punto de regeneracion",
  CRIT_STUN: "Los impactos criticos hacen perder 1 turno al objetivo",
  DADOS_ATAQUE: "+10 ataque x cada dado en juego",
  CRIT_CRIT:
    "Cada ataque critico con la Katana aumenta la probabilidad de critico 1%",
  CRIT_VENENO:
    "Colmillo de Basilisco: los impactos criticos infligen veneno 40 x3T ",
  CRIT_HEAL: "Sadismo:los impactos criticos curan el 5% del HpMax",
  CRIT_HEMO: "Cortante: los impactos criticos provocan hemorragia 50 x3T",
  SPINA: "30% de probabilidad de devolver el daño recibido",
};

export const arrayEquipo = [
  [
    {
      nombre: "Desequipar",
      clave: "0,0",
      indice: "0",
    },
    { nombre: "Desequipar", clave: "0,1", indice: "0" },
    {
      nombre: "Desequipar",
      clave: "0,2",
      indice: "0",
    },
  ],
  [
    [
      //ataque
      [
        {
          nombre: "Espada Maltrecha",
          ataque: 5,
          defensa: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
      ],
      [
        {
          nombre: "Armadura de Caballero",
          ataque: 0,
          defensa: 5,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      ],
      [
        {
          nombre: "Foto Familiar",
          ataque: 1,
          defensa: 1,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 1,
          regeneracion: 0,
        },
      ],
    ],
    [
      //defensa
      [
        {
          nombre: "Espada Maltrecha",
          ataque: 5,
          defensa: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
      ],
      [
        {
          nombre: "Placas Incompletas",
          ataque: 0,
          defensa: 10,
          esquivar: -5,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      ],
      [
        {
          nombre: "Brazalete de Metal",
          ataque: 0,
          defensa: 5,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      ],
    ],
    [
      //agilidad
      [
        {
          nombre: "Daga Oxidada",
          ataque: 3,
          defensa: 0,
          critico: 3,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
      ],
      [
        {
          nombre: "Armadura de Cuero",
          ataque: 0,
          defensa: 1,
          esquivar: 5,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      ],
      [
        {
          nombre: "Anillo Oxidado",
          ataque: 1,
          defensa: 0,
          esquivar: 2,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      ],
    ],
    [
      //maleficio
      [
        {
          nombre: "Varita de Roble",
          ataque: 0,
          defensa: 0,
          critico: 0,
          maleficio: 5,
          curacion: 0,
          vampirismo: 0,
        },
      ],
      [
        {
          nombre: "Vestiduras Oscuras",
          ataque: 0,
          defensa: 1,
          esquivar: 0,
          maleficio: 5,
          curacion: 0,
          regeneracion: 0,
        },
      ],
      [
        {
          nombre: "Anillo de Brujo",
          ataque: 0,
          defensa: 0,
          esquivar: 0,
          critico: 2,
          maleficio: 2,
          curacion: 0,
          regeneracion: 0,
        },
      ],
    ],
    [
      // curacion
      [
        {
          nombre: "Baculo del Sanador",
          ataque: 0,
          defensa: 0,
          maleficio: 0,
          curacion: 5,
        },
      ],
      [
        {
          nombre: "Tunicas del Sanador",
          ataque: 0,
          defensa: 1,
          maleficio: 0,
          curacion: 5,
        },
      ],
      [
        {
          nombre: "Collar del Chamán",
          ataque: 0,
          defensa: 0,
          maleficio: 0,
          curacion: 5,
        },
      ],
    ],
  ],
  [
    //lvl2
    [
      // ataque
      [
        {
          nombre: "Espadon Pesado",
          ataque: 20,
          defensa: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
        {
          nombre: "Espada Larga",
          ataque: 12,
          defensa: 0,
          critico: 5,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
        {
          nombre: "Espada Carmesi",
          ataque: 15,
          defensa: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          vampirismo: 5,
        },
      ],
      [
        {
          nombre: "Armadura de Guerra",
          ataque: 5,
          defensa: 15,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 5,
          regeneracion: 1,
        },
        {
          nombre: "Armadura Carmesi",
          ataque: 5,
          defensa: 10,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 3,
          vampirismo: 5,
        },
      ],
      [
        {
          nombre: "Tecnicas de lucha I",
          ataque: 3,
          defensa: 3,
          esquivar: 3,
          critico: 3,
          maleficio: 0,
          curacion: 0,
          regeneracion: 2,
          vampirismo: 0,
        },
      ],
    ],
    [
      // defensa
      [
        {
          nombre: "Escudo afilado",
          ataque: 5,
          defensa: 10,
          critico: 3,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
      ],
      [
        {
          nombre: "Armadura de Vitalidad",
          ataque: 0,
          defensa: 20,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 5,
          regeneracion: 3,
          vidaMaxima: 10,
        },
      ],
      [
        {
          nombre: "Manual: escudero I",
          ataque: 0,
          defensa: 10,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      ],
    ],
    [
      [
        {
          nombre: "Bisturí de Guerra",
          ataque: 5,
          defensa: 0,
          critico: 20,
          maleficio: 0,
          curacion: 5,
          vampirismo: 0,
        },
        {
          nombre: "Daga Sacatripas",
          ataque: 13,
          defensa: 0,
          critico: 10,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
        {
          nombre: "Cuchillo de Bota",
          ataque: 3,
          defensa: 0,
          critico: 20,
          esquivar: 10,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
      ],
      [
        {
          nombre: "Armadura de Escamas",
          ataque: 0,
          defensa: 5,
          critico: 10,
          esquivar: 5,
          maleficio: 0,
          curacion: 0,
          regeneracion: 3,
        },
        {
          nombre: "Mallas de aluminio",
          ataque: 0,
          defensa: 5,
          critico: 5,
          esquivar: 10,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      ],
      [
        {
          nombre: "Cola de mono",
          ataque: 0,
          defensa: 0,
          esquivar: 10,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
        {
          nombre: "Manual de cirugía I",
          ataque: 3,
          defensa: 0,
          esquivar: 0,
          critico: 10,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      ],
    ],
    [
      [
        {
          nombre: "Baculo de Obsidiana",
          ataque: 5,
          defensa: 0,
          critico: 5,
          maleficio: 20,
          curacion: 0,
          vampirismo: 0,
        },
        {
          nombre: "Absorbealmas",
          ataque: 10,
          defensa: 0,
          critico: 0,
          maleficio: 5,
          curacion: 5,
          vampirismo: 10,
        },
      ],
      [
        {
          nombre: "Tunica Cosechaoscura",
          ataque: 5,
          defensa: 5,
          esquivar: 0,
          maleficio: 5,
          curacion: 5,
          vampirismo: 5,
        },
        {
          nombre: "Aura Oscura",
          ataque: 0,
          defensa: -5,
          esquivar: 0,
          maleficio: 25,
          curacion: 0,
          regeneracion: 0,
        },
      ],
      [
        {
          nombre: "Talisman maldito",
          ataque: 0,
          defensa: 0,
          esquivar: 0,
          critico: 5,
          maleficio: 10,
          curacion: 0,
          regeneracion: 0,
        },
        {
          nombre: "Cristal oscuro",
          ataque: 3,
          defensa: 0,
          esquivar: 0,
          critico: 0,
          maleficio: 5,
          curacion: 5,
          vampirismo: 5,
        },
      ],
    ],
    [
      [
        {
          nombre: "Lucero del Alba",
          ataque: 10,
          defensa: 0,
          maleficio: 0,
          curacion: 15,
        },
        {
          nombre: "Manos curativas",
          ataque: 3,
          defensa: 0,
          maleficio: 0,
          curacion: 30,
        },
      ],
      [
        {
          nombre: "Aura de luz",
          ataque: 0,
          defensa: 1,
          maleficio: 0,
          curacion: 30,
        },
        {
          nombre: "Placas de Templario",
          ataque: 0,
          defensa: 15,
          maleficio: 0,
          curacion: 15,
        },
      ],
      [
        {
          nombre: "Libro Sagrado",
          ataque: 5,
          defensa: 0,
          maleficio: 0,
          curacion: 15,
        },
        {
          nombre: "Remedio Casero",
          ataque: 0,
          defensa: 0,
          maleficio: 0,
          curacion: 20,
        },
      ],
    ],
  ],
  [
    //lvl3
    [
      // ataque
      [
        {
          nombre: "Skeggöx Colerico",
          ataque: 30,
          defensa: 0,
          critico: 15,
          maleficio: 0,
          curacion: 0,
          vampirismo: 25,
        },
        {
          //3001
          nombre: "Maza del Gigante",
          ataque: 70,
          critico: 5,
          vampirismo: 0,
          defensa: 0,
          esquivar: -10,
          defensaMagica: 2,
          vidaMaxima: 30,
          regeneracion: 5,
          maleficio: 0,
          curacion: 0,
          efecto: EFECTOS_EQUIPO.CRIT_STUN,
        },
        // {
        //   nombre: "Espada Carmesi",
        //   ataque: 15,
        //   defensa: 0,
        //   critico: 0,
        //   maleficio: 0,
        //   curacion: 0,
        //   vampirismo: 5,
        // },
      ],
      [
        {
          nombre: "Pecho descubierto",
          ataque: 10,
          defensa: 0,
          esquivar: 0,
          critico: 5,
          maleficio: 0,
          curacion: 0,
          regeneracion: 3,
          vampirismo: 10,
          vidaMaxima: 15,
        },
        {
          nombre: "Hombro reforzado",
          ataque: 0,
          defensa: 10,
          esquivar: 20,
          critico: 10,
          maleficio: 0,
          curacion: 15,
          regeneracion: 3,
          vampirismo: 0,
          vidaMaxima: 10,
        },
      ],
      [
        {
          nombre: "Sangre de Gigante",
          ataque: 0,
          defensa: 0,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 5,
          vidaMaxima: 30,
          vampirismo: 0,
          efecto: EFECTOS_EQUIPO.VIDA_ATAQUE,
        },
      ],
    ],
    [
      // defensa 1
      [
        {
          nombre: "Maza del Gigante",
          ataque: 70,
          critico: 5,
          vampirismo: 0,
          defensa: 0,
          esquivar: -10,
          defensaMagica: 2,
          vidaMaxima: 30,
          regeneracion: 5,
          maleficio: 0,
          curacion: 0,
          efecto: EFECTOS_EQUIPO.CRIT_STUN,
        },
        {
          //3101
          nombre: "Spina",
          ataque: 15,
          vampirismo: 5,
          critico: 5,
          defensa: 30,
          regeneracion: 3,
          esquivar: 5,
          maleficio: 0,
          curacion: 0,
          efecto: EFECTOS_EQUIPO.SPINA,
        },
      ],
      [
        {
          nombre: "Placas de Hierrocrater",
          ataque: 0,
          defensa: 50,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 10,
          regeneracion: 5,
          vidaMaxima: 15,
        },
        {
          nombre: "Armadura de vitalidad II",
          ataque: 0,
          defensa: 25,
          defensaMagica: 1,
          esquivar: -5,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 10,
          vidaMaxima: 40,
        },
      ],
      [
        {
          nombre: "Coraje",
          ataque: 0,
          defensa: 10,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
          efecto: EFECTOS_EQUIPO.DADOS_ATAQUE,
        },
        {
          nombre: "Corazon del Gigante",
          ataque: 0,
          defensa: 15,
          defensaMagica: 1,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 5,
          vidaMaxima: 25,
          efecto: EFECTOS_EQUIPO.VIDA_REGEN,
        },
      ],
    ],
    [
      //agilidad 2
      [
        {
          nombre: "Suspiro de muerte",
          ataque: 35,
          critico: 30,
          defensa: 0,
          maleficio: 20,
          curacion: 0,
          vampirismo: 0,
        },
        {
          //3201
          nombre: "Katana",
          ataque: 20,
          defensa: 0,
          critico: 10,
          vampirismo: 15,
          maleficio: 0,
          curacion: 0,
          efecto: EFECTOS_EQUIPO.CRIT_CRIT,
        },
        {
          nombre: "Colmillo de Basilisco",
          ataque: 10,
          defensa: 0,
          critico: 50,
          esquivar: 20,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
          efecto: EFECTOS_EQUIPO.CRIT_VENENO,
        },
      ],
      [
        {
          nombre: "Sombra",
          ataque: 0,
          defensa: 0,
          critico: 0,
          esquivar: 30,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
        {
          nombre: "Armadura Samurai",
          ataque: 5,
          critico: 5,
          vampirismo: 5,
          defensa: 15,
          defensaMagica: 2,
          esquivar: 10,
          vidaMaxima: 15,
          regeneracion: 3,
          maleficio: 0,
          curacion: 0,
        },
        {
          nombre: "Armadura Placaopaca",
          ataque: 0,
          critico: 0,
          defensa: 20,
          defensaMagica: 2,
          esquivar: 20,
          maleficio: 0,
          curacion: 0,
          regeneracion: 3,
        },
      ],
      [
        {
          nombre: "Zapatos de viento",
          ataque: 0,
          defensa: 0,
          esquivar: 10,
          critico: 10,
          maleficio: 0,
          curacion: 0,
          regeneracion: 20,
        },
        {
          nombre: "Hagakure",
          ataque: 0,
          critico: 10,
          defensa: 0,
          defensaMagica: 2,
          esquivar: 10,
          vidaMaxima: 10,
          regeneracion: 10,
          maleficio: 0,
          curacion: 10,
        },
        {
          //3222
          nombre: "Sadismo",
          ataque: 10,
          critico: 15,
          defensa: 0,
          defensaMagica: 2,
          esquivar: 0,
          vidaMaxima: 0,
          regeneracion: 0,
          maleficio: 10,
          curacion: 0,
          efecto: EFECTOS_EQUIPO.CRIT_HEAL,
        },
      ],
    ],
    [
      // maleficio 3
      [
        {
          nombre: "Vara Desalmada",
          ataque: 20,
          critico: 15,
          vampirismo: 5,
          defensa: 0,
          maleficio: 30,
          curacion: 0,
        },
        {
          nombre: "Botella de Whisky Rota",
          ataque: 10,
          vampirismo: 10,
          critico: 0,
          defensa: 0,
          vidaMaxima: 10,
          regeneracion: 6,
          maleficio: 10,
          curacion: 5,
          efectos: EFECTOS_EQUIPO.CRIT_HEMO,
        },
        {
          nombre: "Daga de Cristal",
          ataque: 15,
          vampirismo: 0,
          critico: 10,
          defensa: 0,
          defensaMagica: 1,
          vidaMaxima: 0,
          regeneracion: 0,
          maleficio: 20,
          curacion: 10,
          efectos: EFECTOS_EQUIPO.CRIT_HEMO,
        },
      ],
      [
        {
          nombre: "Espiritu de Medea",
          ataque: 0,
          defensa: 10,
          esquivar: 0,
          maleficio: 25,
          curacion: 0,
          vampirismo: 5,
        },
        {
          nombre: "Tunica de Alquimista",
          ataque: 0,
          vampirismo: 10,
          defensa: 10,
          esquivar: 5,
          regeneracion: 5,
          vidaMaxima: 15,
          maleficio: 10,
          curacion: 10,
        },
        {
          nombre: "Tunica de Aristócrata",
          ataque: 0,
          vampirismo: 0,
          defensa: 15,
          defensaMagica: 1,
          esquivar: 30,
          regeneracion: 5,
          vidaMaxima: 10,
          maleficio: 15,
          curacion: 15,
        },
      ],
      [
        {
          nombre: "Magia prohibida IX",
          ataque: 5,
          critico: 15,
          vampirismo: 5,
          defensa: 0,
          esquivar: 0,
          maleficio: 25,
          curacion: 0,
          regeneracion: 0,
        },
        {
          //3321
          nombre: "Alquimia VII",
          ataque: 5,
          critico: 0,
          vampirismo: 10,
          defensa: 0,
          esquivar: 0,
          vidaMaxima: 10,
          regeneracion: 3,
          maleficio: 5,
          curacion: 10,
          efecto: EFECTOS_EQUIPO.REGEN_STATS,
        },
        {
          nombre: "Reloj Hechizado",
          ataque: 0,
          critico: 0,
          vampirismo: 0,
          defensa: 0,
          defensaMagica: 2,
          esquivar: 0,
          vidaMaxima: 0,
          regeneracion: 0,
          maleficio: 10,
          curacion: 10,
        },
      ],
    ],
    [
      //healer 4
      [
        {
          nombre: "Justiciera de Plata",
          ataque: 25,
          critico: 10,
          vampirismo: 5,
          defensa: 0,
          defensaMagica: 1,
          vidaMaxima: 10,
          regeneracion: 3,
          maleficio: 0,
          curacion: 20,
        },
        {
          nombre: "Cetro Milagroso",
          ataque: 5,
          critico: 10,
          defensa: 0,
          defensaMagica: 1,
          maleficio: 0,
          curacion: 50,
        },
      ],
      [
        {
          nombre: "Tunica Inmaculada",
          ataque: 0,
          critico: 10,
          defensa: 10,
          defensaMagica: 2,
          maleficio: 0,
          curacion: 30,
        },
        {
          nombre: "Arm. de Plata pulida",
          ataque: 0,
          defensa: 25,
          defensaMagica: 2,
          esquivar: 10,
          vidaMaxima: 20,
          regeneracion: 3,
          maleficio: 0,
          curacion: 10,
        },
      ],
      [
        //2
        {
          //0
          nombre: "Amuleto de Resurreccion",
          ataque: 0,
          critico: 10,
          defensaMagica: 1,
          defensa: 10,
          maleficio: 0,
          curacion: 30,
          efecto: EFECTOS_EQUIPO.VIDA_RESURRECCION,
        },
        {
          nombre: "Condecoracion del Papa",
          ataque: 10,
          critico: 5,
          vampirismo: 5,
          defensaMagica: 1,
          defensa: 0,
          vidaMaxima: 10,
          regeneracion: 3,
          maleficio: 0,
          curacion: 10,
        },
      ],
    ],
  ],
];
//NIVEL-SPEC-TIPO-OBJETO
export const EQUIPO = {
  LVL1: {
    ATAQUE: {
      ARMA: {
        ESPADA_MALTRECHA: {
          nombre: "Espada Maltrecha",
          ataque: 5,
          defensa: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
      },
      ARMADURA: {
        ARMADURA_CABALLERO: {
          nombre: "Armadura de Caballero",
          defensa: 5,
          esquivar: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      },
      JOYA: {
        FOTO_FAMILIAR: {
          nombre: "Foto Familiar",
          ataque: 1,
          defensa: 1,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 1,
          regeneracion: 0,
        },
      },
    },
    AGILIDAD: {
      ARMA: {
        DAGA_OXIDADA: {
          nombre: "Daga Oxidada",
          ataque: 3,
          defensa: 0,
          critico: 3,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
      },
      ARMADURA: {
        ARMADURA_CUERO: {
          nombre: "Armadura de Cuero",
          defensa: 1,
          esquivar: 5,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      },
      JOYA: {
        ANILLO_OXIDADO: {
          nombre: "Anillo Oxidado",
          ataque: 1,
          defensa: 0,
          esquivar: 2,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      },
    },
    DEFENSA: {
      ARMA: {
        ESPADA_MALTRECHA: {
          nombre: "Espada Maltrecha",
          ataque: 5,
          defensa: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          vampirismo: 0,
        },
      },
      ARMADURA: {
        PLACAS_LVL1: {
          nombre: "Placas Incompletas",
          defensa: 10,
          esquivar: -5,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      },
      JOYA: {
        BRAZALETE_METAL: {
          nombre: "Brazalete de Metal",
          ataque: 0,
          defensa: 5,
          esquivar: 0,
          critico: 0,
          maleficio: 0,
          curacion: 0,
          regeneracion: 0,
        },
      },
    },
    MALEFICIO: {
      ARMA: {
        VARITA_ROBLE: {
          nombre: "Varita de Roble",
          ataque: 0,
          defensa: 0,
          critico: 0,
          maleficio: 5,
          curacion: 0,
          vampirismo: 0,
        },
      },
      ARMADURA: {
        VESTIDURAS_OSCURAS: {
          nombre: "Vestiduras Oscuras",
          defensa: 1,
          esquivar: 0,
          maleficio: 5,
          curacion: 0,
          regeneracion: 0,
        },
      },
      JOYA: {
        ANILLO_BRUJO: {
          nombre: "Anillo de Brujo",
          ataque: 0,
          defensa: 0,
          esquivar: 0,
          critico: 2,
          maleficio: 2,
          curacion: 0,
          regeneracion: 0,
        },
      },
    },
    CURACION: {
      ARMA: {
        BACULO_SANADOR: {
          nombre: "Baculo del Sanador",
          ataque: 0,
          defensa: 0,
          maleficio: 0,
          curacion: 5,
        },
      },
      ARMADURA: {
        TUNICA_SANADOR: {
          nombre: "Tunicas del Sanador",
          ataque: 0,
          defensa: 1,
          maleficio: 0,
          curacion: 5,
        },
      },
      JOYA: {
        COLLAR_CHAMAN: {
          nombre: "Collar del Chamán",
          ataque: 0,
          defensa: 0,
          maleficio: 0,
          curacion: 5,
        },
      },
    },
  },
  LVL2: {
    ATAQUE: { ARMA: {}, ARMADURA: {}, JOYA: {} },
    DEFENSA: { ARMA: {}, ARMADURA: {}, JOYA: {} },
    MALEFICIO: { ARMA: {}, ARMADURA: {}, JOYA: {} },
    CURACION: { ARMA: {}, ARMADURA: {}, JOYA: {} },
  },
  LVL3: {
    ATAQUE: { ARMA: {}, ARMADURA: {}, JOYA: {} },
    DEFENSA: { ARMA: {}, ARMADURA: {}, JOYA: {} },
    MALEFICIO: {
      ARMA: {},
      ARMADURA: {},
      JOYA: {
        COLLAR_OBSIDIANA: {
          nombre: "Collar de Obsidiana",
          ataque: 15,
          defensa: 0,
          maleficio: 30,
          curacion: 0,
        },
      },
    },
    CURACION: { ARMA: {}, ARMADURA: {}, JOYA: {} },
  },
};
