const personajeEdit = {
  ...statsBase.mageArcano,
  vida: statsBase.mageArcano.vidaBase,
  regeneracion: statsBase.mageArcano.regeneracionBase,
  energia: statsBase.mageArcano.energiaMax,
  reservaEnergia: 0,
  ataque: statsBase.mageArcano.ataqueBase,
  defensa: statsBase.mageArcano.defensaBase,
  defensaMagica: statsBase.mageArcano.defensaMagicaBase,
  critico: statsBase.mageArcano.criticoBase,
  esquivar: statsBase.mageArcano.esquivarBase,
  curacion: statsBase.mageArcano.curacionBase,
  maleficio: statsBase.mageArcano.maleficioBase,
  vampirismo: statsBase.mageArcano.vampirismoBase,
};

export const stats = {
  warriorBersek: {
    ...statsBase.warriorBersek,
    vida: statsBase.warriorBersek.vidaBase,
    vidaMaxima: statsBase.warriorBersek.vidaBase,
    regeneracion: statsBase.warriorBersek.regeneracionBase,
    energia: statsBase.warriorBersek.energiaMax,
    reservaEnergia: 0,
    ataque: statsBase.warriorBersek.ataqueBase,
    defensa: statsBase.warriorBersek.defensaBase,
    defensaMagica: statsBase.warriorBersek.defensaMagicaBase,
    critico: statsBase.warriorBersek.criticoBase,
    esquivar: statsBase.warriorBersek.esquivarBase,
    curacion: statsBase.warriorBersek.curacionBase,
    maleficio: statsBase.warriorBersek.maleficioBase,
    vampirismo: statsBase.warriorBersek.vampirismoBase,
  },
  warriorProtec: {
    ...statsBase.warriorProtec,
    vida: statsBase.warriorProtec.vidaBase,
    vidaMaxima: statsBase.warriorProtec.vidaBase,
    regeneracion: statsBase.warriorProtec.regeneracionBase,
    energia: statsBase.warriorProtec.energiaMax,
    reservaEnergia: 0,
    ataque: statsBase.warriorProtec.ataqueBase,
    defensa: statsBase.warriorProtec.defensaBase,
    defensaMagica: statsBase.warriorProtec.defensaMagicaBase,
    critico: statsBase.warriorProtec.criticoBase,
    esquivar: statsBase.warriorProtec.esquivarBase,
    curacion: statsBase.warriorProtec.curacionBase,
    maleficio: statsBase.warriorProtec.maleficioBase,
    vampirismo: statsBase.warriorProtec.vampirismoBase,
  },
  rogueSicario: {
    ...statsBase.rogueSicario,
    vida: statsBase.rogueSicario.vidaBase,
    vidaMaxima: statsBase.rogueSicario.vidaBase,
    regeneracion: statsBase.rogueSicario.regeneracionBase,
    energia: statsBase.rogueSicario.energiaMax,
    reservaEnergia: 0,
    ataque: statsBase.rogueSicario.ataqueBase,
    defensa: statsBase.rogueSicario.defensaBase,
    defensaMagica: statsBase.rogueSicario.defensaMagicaBase,
    critico: statsBase.rogueSicario.criticoBase,
    esquivar: statsBase.rogueSicario.esquivarBase,
    curacion: statsBase.rogueSicario.curacionBase,
    maleficio: statsBase.rogueSicario.maleficioBase,
    vampirismo: statsBase.rogueSicario.vampirismoBase,
  },
  rogueMalabarista: {
    ...statsBase.rogueMalabarista,
    vida: statsBase.rogueMalabarista.vidaBase,
    vidaMaxima: statsBase.rogueMalabarista.vidaBase,
    regeneracion: statsBase.rogueMalabarista.regeneracionBase,
    energia: statsBase.rogueMalabarista.energiaMax,
    reservaEnergia: 0,
    ataque: statsBase.rogueMalabarista.ataqueBase,
    defensa: statsBase.rogueMalabarista.defensaBase,
    defensaMagica: statsBase.rogueMalabarista.defensaMagicaBase,
    critico: statsBase.rogueMalabarista.criticoBase,
    esquivar: statsBase.rogueMalabarista.esquivarBase,
    curacion: statsBase.rogueMalabarista.curacionBase,
    maleficio: statsBase.rogueMalabarista.maleficioBase,
    vampirismo: statsBase.rogueMalabarista.vampirismoBase,
  },
  warlockMasas: {
    ...statsBase.warlockMasas,
    vida: statsBase.warlockMasas.vidaBase,
    vidaMaxima: statsBase.warlockMasas.vidaBase,
    regeneracion: statsBase.warlockMasas.regeneracionBase,
    energia: statsBase.warlockMasas.energiaMax,
    reservaEnergia: 0,
    ataque: statsBase.warlockMasas.ataqueBase,
    defensa: statsBase.warlockMasas.defensaBase,
    defensaMagica: statsBase.warlockMasas.defensaMagicaBase,
    critico: statsBase.warlockMasas.criticoBase,
    esquivar: statsBase.warlockMasas.esquivarBase,
    curacion: statsBase.warlockMasas.curacionBase,
    maleficio: statsBase.warlockMasas.maleficioBase,
    vampirismo: statsBase.warlockMasas.vampirismoBase,
  },
  warlockDestruccion: {
    ...statsBase.warlockDestruccion,
    vida: statsBase.warlockDestruccion.vidaBase,
    vidaMaxima: statsBase.warlockDestruccion.vidaBase,
    regeneracion: statsBase.warlockDestruccion.regeneracionBase,
    energia: statsBase.warlockDestruccion.energiaMax,
    reservaEnergia: 0,
    ataque: statsBase.warlockDestruccion.ataqueBase,
    defensa: statsBase.warlockDestruccion.defensaBase,
    defensaMagica: statsBase.warlockDestruccion.defensaMagicaBase,
    critico: statsBase.warlockDestruccion.criticoBase,
    esquivar: statsBase.warlockDestruccion.esquivarBase,
    curacion: statsBase.warlockDestruccion.curacionBase,
    maleficio: statsBase.warlockDestruccion.maleficioBase,
    vampirismo: statsBase.warlockDestruccion.vampirismoBase,
  },
  mageArcano: {
    ...statsBase.mageArcano,
    vida: statsBase.mageArcano.vidaBase,
    vidaMaxima: statsBase.mageArcano.vidaBase,
    regeneracion: statsBase.mageArcano.regeneracionBase,
    energia: statsBase.mageArcano.energiaMax,
    reservaEnergia: 0,
    ataque: statsBase.mageArcano.ataqueBase,
    defensa: statsBase.mageArcano.defensaBase,
    defensaMagica: statsBase.mageArcano.defensaMagicaBase,
    critico: statsBase.mageArcano.criticoBase,
    esquivar: statsBase.mageArcano.esquivarBase,
    curacion: statsBase.mageArcano.curacionBase,
    maleficio: statsBase.mageArcano.maleficioBase,
    vampirismo: statsBase.mageArcano.vampirismoBase,
  },
  mageSanador: {
    ...statsBase.mageSanador,
    vida: statsBase.mageSanador.vidaBase,
    vidaMaxima: statsBase.mageSanador.vidaBase,
    regeneracion: statsBase.mageSanador.regeneracionBase,
    energia: statsBase.mageSanador.energiaMax,
    reservaEnergia: 0,
    ataque: statsBase.mageSanador.ataqueBase,
    defensa: statsBase.mageSanador.defensaBase,
    defensaMagica: statsBase.mageSanador.defensaMagicaBase,
    critico: statsBase.mageSanador.criticoBase,
    esquivar: statsBase.mageSanador.esquivarBase,
    curacion: statsBase.mageSanador.curacionBase,
    maleficio: statsBase.mageSanador.maleficioBase,
    vampirismo: statsBase.mageSanador.vampirismoBase,
  },
};
